name: whatdatbus
description: An app to detect buses and their respective numbers.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.0
  cupertino_icons: ^1.0.5
  flutter_tts: ^3.5.0
  google_ml_kit: ^0.5.1
  image: ^3.2.0
  shared_preferences: ^2.0.15
  tflite: 1.1.1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter:
  assets:
    - assets/icons/
    - assets/models/

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/icon.png
